name: Archive Test
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Downloading the archive
      run: |
        sudo apt install wget -y
        wget -O God-Of-War-AnkerGames.zip https://tunnel5.dlproxy.uk/download/vhWcE3IuQ4-zhOZudxXeOohFz25dEzYq3h-ZwsKsdXg9IsKQtOiEHXjO7FpdLY27ViecZvVNl8hRXzTNQnIzacOU5Gmf7hL-EsquKhK3Pqxgro-4TBzOZQ8kVg9hvU6YJx2GlcFiLRxzmW7p4y1Yv0lFLesilIU6zi_myLoyBMqKEovi7Ytr_o7HRJVLzl40xJjPxx58ost28y0A9WCsAFlVw2OSyAvVENHyqmK5cG8loXX8sq_X5LHNxAZN89jAsYgBw6854ehLv7sL5KBsg8e2HSDhj2F_iTF_9kt20NTtrs6ZiiM8k0ukyRjc56R4GPNYFaRANqvf-uG37oHO-YHYY54DA6wb7sGbn_D_IyzXfewOi0XryU49jy1pFh_iVyXBNoyzrHSn7qGZT30q4Q?sig=V5nDbRxlXQ9s7i7sZ2CO9mqWwTk9ZKh0RJsUbyuPDMM
        
    - name: Checking archive
      run: bash archive-test.sh
